export interface IndianState {
  code: string;
  name: string;
}

export const INDIAN_STATES: IndianState[] = [
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CG', name: 'Chhattisgarh' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HR', name: 'Haryana' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'MN', name: 'Manipur' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OD', name: 'Odisha' },
  { code: 'PB', name: 'Punjab' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TS', name: 'Telangana' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UK', name: 'Uttarakhand' },
  { code: 'WB', name: 'West Bengal' },
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'JK', name: 'Jammu and Kashmir' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'PY', name: 'Puducherry' },
];

export const CITIES_BY_STATE: Record<string, string[]> = {
  AP: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Tirupati', 'Rajahmundry', 'Kadapa'],
  AR: ['Itanagar', 'Naharlagun', 'Pasighat'],
  AS: ['Guwahati', 'Dibrugarh', 'Silchar', 'Jorhat', 'Tezpur', 'Nagaon'],
  BR: [
  'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga', 'Purnia',
  'Arrah', 'Begusarai', 'Katihar', 'Munger', 'Chhapra', 'Danapur',
  'Bettiah', 'Saharsa', 'Sasaram', 'Hajipur', 'Dehri', 'Siwan',
  'Motihari', 'Nawada', 'Bagaha', 'Buxar', 'Kishanganj', 'Sitamarhi',
  'Jamalpur', 'Jehanabad', 'Aurangabad', 'Lakhisarai', 'Madhubani',
  'Samastipur', 'Bihar Sharif', 'Gopalganj', 'Araria',
],
  CG: ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon'],
  GA: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
  GJ: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Gandhinagar', 'Junagadh'],
  HR: ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Karnal', 'Hisar', 'Rohtak', 'Sonipat'],
  HP: ['Shimla', 'Manali', 'Dharamshala', 'Solan', 'Mandi', 'Kullu'],
  JH: [
  'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh',
  'Giridih', 'Ramgarh', 'Phusro', 'Dumka', 'Chirkunda', 'Chaibasa',
  'Gumla', 'Godda', 'Sahibganj', 'Pakur', 'Chatra', 'Latehar',
  'Simdega', 'Lohardaga', 'Koderma', 'Jhumri Tilaiya', 'Medininagar',
],
  KA: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi', 'Belagavi', 'Davangere', 'Shivamogga', 'Tumakuru'],
  KL: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur', 'Kollam', 'Kannur', 'Alappuzha'],
  MP: [
  'Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain', 'Sagar',
  'Satna', 'Rewa', 'Ratlam', 'Dewas', 'Murwara', 'Singrauli',
  'Burhanpur', 'Khandwa', 'Bhind', 'Chhindwara', 'Guna', 'Shivpuri',
  'Vidisha', 'Chhatarpur', 'Damoh', 'Mandsaur', 'Khargone', 'Neemuch',
  'Pithampur', 'Hoshangabad', 'Itarsi', 'Sehore', 'Betul', 'Seoni',
  'Datia', 'Nagda', 'Morena',
],
  MH: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Thane', 'Aurangabad', 'Solapur', 'Kolhapur', 'Amravati', 'Navi Mumbai'],
  MN: ['Imphal', 'Thoubal', 'Kakching'],
  ML: ['Shillong', 'Tura', 'Jowai'],
  MZ: ['Aizawl', 'Lunglei', 'Champhai'],
  NL: ['Kohima', 'Dimapur', 'Mokokchung'],
  OD: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri'],
  PB: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali'],
  RJ: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Ajmer', 'Bikaner', 'Alwar', 'Bhilwara'],
  SK: ['Gangtok', 'Namchi', 'Gyalshing'],
  TN: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tirunelveli', 'Erode', 'Vellore'],
  TS: ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam', 'Secunderabad'],
  TR: ['Agartala', 'Udaipur', 'Dharmanagar'],
  UP: [
  'Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Meerut', 'Noida', 'Ghaziabad',
  'Prayagraj', 'Bareilly', 'Aligarh', 'Moradabad', 'Saharanpur', 'Gorakhpur',
  'Firozabad', 'Jhansi', 'Muzaffarnagar', 'Mathura', 'Rampur', 'Shahjahanpur',
  'Farrukhabad', 'Mau', 'Hapur', 'Etawah', 'Mirzapur', 'Bulandshahr',
  'Sambhal', 'Amroha', 'Hardoi', 'Fatehpur', 'Raebareli', 'Orai',
  'Sitapur', 'Bahraich', 'Modinagar', 'Unnao', 'Jaunpur', 'Lakhimpur',
  'Hathras', 'Banda', 'Pilibhit', 'Barabanki', 'Khurja', 'Gonda',
  'Mainpuri', 'Auraiya', 'Deoria', 'Faizabad', 'Basti', 'Ballia',
],
  UK: ['Dehradun', 'Haridwar', 'Nainital', 'Roorkee', 'Haldwani', 'Rishikesh'],
  WB: [
  'Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri', 'Bardhaman',
  'Malda', 'Kharagpur', 'Baharampur', 'Krishnanagar', 'Naihati',
  'Serampore', 'Ranaghat', 'Haldia', 'Raiganj', 'Jalpaiguri',
  'Alipurduar', 'Cooch Behar', 'Bankura', 'Purulia', 'Medinipur',
  'Balurghat', 'Basirhat', 'Barasat', 'Chandannagar', 'Bolpur',
  'Contai', 'Darjeeling', 'Kalimpong', 'Suri', 'Kalyani', 'Barrackpore',
],
  AN: ['Port Blair'],
  CH: ['Chandigarh'],
  DN: ['Daman', 'Silvassa', 'Diu'],
  DL: ['New Delhi', 'Dwarka', 'Rohini', 'Karol Bagh', 'Saket', 'Pitampura', 'Janakpuri'],
  JK: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla'],
  LA: ['Leh', 'Kargil'],
  LD: ['Kavaratti'],
  PY: ['Puducherry', 'Karaikal'],
};