
auth.token=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

defaults.org=totostore
defaults.project=react-native

defaults.url=https://sentry.io/
