export const colors = {
  background: '#F7F8FA',
  surface: '#FFFFFF',
  surfaceContainer: '#EEF1F3',
  surfaceContainerLow: '#F3F5F7',
  primary: '#1B1F22',
  accent: '#B9E857',
  accentSoft: '#E9F7BF',
  onSurface: '#171B1D',
  onSurfaceVariant: '#5E6468',
  outline: '#D6DCE0',
  outlineVariant: '#E6EAEE',
  onPrimary: '#FFFFFF',
  onAccent: '#111111',
  error: '#D32F2F',
  errorContainer: '#FDECEC',
  success: '#2E7D32',
  orange: '#F59E0B',
};
